apiVersion: k8s-function.io/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: k8s-function
    app.kubernetes.io/managed-by: kustomize
  name: function-sample
spec:
  runtimeImage: "python:3.9"
  replicas: 1
  code: |
    import os
    print(f'hello')