apiVersion: k8s-function.io/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: k8s-function
    app.kubernetes.io/managed-by: kustomize
  name: function-sample
spec:
  # TODO(user): Add fields here
