name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create manifests
      run: make generate && make manifests
      
    - name: Build manager
      run: make
      
    - name: Create distro
      run: make build-installer
