name: CI Builds

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2
    
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Build
      run: make
      
    - name: Create distro
      run: make build-installer
