
on:
  push:
    tags: "release-v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2
    
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Build
      run: make
      
    - name: Build installer
      run: make build-installer
      
    - name: Build Docker Image
      run: make docker-buildx IMG=piased/k8s-function:v0.0.0
      
    - name: Get version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}"
    
    - name: Upload install.yaml
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: install.yaml
        # A file, directory or wildcard pattern that describes what to upload
        path: dist/install.yaml
        # The desired behavior if no files are found using the provided path.          
