name: Release Builds

on:
  push:
    tags: "v*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  IMAGE_NAME: k8s-function
  VERSION: ${{ github.ref_name }}

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.2
    
    - name: Checkout source
      uses: actions/checkout@v4
      
    - name: Build
      run: make
      
    - name: Build installer
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        make build-installer IMG=$IMAGE_ID:$VERSION
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        make docker-buildx IMG=$IMAGE_ID:$VERSION

    - name: create release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: false
        generate_release_notes: false
        append_body: false
        files: dist/install.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


